Fixed Semaphor issue that led to hermit crashing when starting threads
hermit-os/pthread-embedded pull request #2
Opened 2024-05-29 10:55 UTC by CarlWachter

CC: @mkroening

2024-05-29 13:33 UTC, mkroening requested changes
Thanks!

Could you remove the merge commit?

2024-05-29 13:33 UTC, mkroening commented on platform/psp/psp_osal.c
Where does this file come from?
Why does it change?

2024-05-29 13:33 UTC, mkroening commented on platform/hermit/syscall.h
> +int32_t sys_sem_post(HermitSemaphore* sem);
```suggestion
int sys_sem_post(HermitSemaphore* sem);
```

2024-05-30 12:14 UTC, CarlWachter commented on platform/psp/psp_osal.c
It is the exact same content, but automake fixed the formatting. Since the old version is an unreadable one liner, i think this is an improvement.

2024-05-30 12:16 UTC, CarlWachter commented
> Could you remove the merge commit?

Done

2024-05-31 10:45 UTC, mkroening approved these changes
Looks good to me!

Is this WIP?

2024-05-31 11:03 UTC, CarlWachter commented
It is very WIP. pshared should ofc be 0, since the semaphore is not created by the kernel otherwise. This technically works, but it breaks crucial functions like join.

Turning pshared to 0, does however lead to a page fault during pthread_init, in the acquisition of an internal mutex in the kernel (this one https://github.com/hermit-os/kernel/blob/1fe04765a9135fdbf4c5a2a0b6eb3e4590cbdf9c/src/synch/semaphore.rs#L77).

Could not find the actual cause of the issue yet.

2024-06-04 10:03 UTC, merged